package db

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// ExportMermaid generates a Mermaid ER-diagram from a SchemaAST.
func ExportMermaid(schema *SchemaAST) string {
	if schema == nil || len(schema.Tables) == 0 {
		return "erDiagram\n"
	}

	var sb strings.Builder
	sb.WriteString("erDiagram\n")

	// Sort table names for deterministic output
	var tableNames []string
	for name := range schema.Tables {
		tableNames = append(tableNames, name)
	}
	sort.Strings(tableNames)

	// Render entity cards
	for _, tName := range tableNames {
		tbl := schema.Tables[tName]
		sb.WriteString(fmt.Sprintf("    %s {\n", tbl.Name))
		for _, col := range tbl.Columns {
			colType := col.DataType
			if colType == "" {
				colType = "string"
			}
			colType = strings.ReplaceAll(colType, " ", "_")
			keyMarker := ""
			if col.IsPK {
				keyMarker = " PK"
			}
			sb.WriteString(fmt.Sprintf("        %s %s%s\n", colType, col.Name, keyMarker))
		}
		sb.WriteString("    }\n")
	}

	// Render relations (Foreign Keys)
	for _, tName := range tableNames {
		tbl := schema.Tables[tName]
		for _, fk := range tbl.ForeignKeys {
			if _, exists := schema.Tables[fk.ToTable]; exists {
				sb.WriteString(fmt.Sprintf("    %s }o--|| %s : \"fk_%s_%s\"\n", tbl.Name, fk.ToTable, tbl.Name, fk.FromColumn))
			}
		}
	}

	return sb.String()
}

// ExportFullDDL generates standard SQL DDL statements from a SchemaAST.
func ExportFullDDL(schema *SchemaAST) string {
	if schema == nil || len(schema.Tables) == 0 {
		return "-- Empty schema\n"
	}

	var sb strings.Builder
	sb.WriteString("-- Auto-generated by Tahr Database ER Diagram\n\n")

	var tableNames []string
	for name := range schema.Tables {
		tableNames = append(tableNames, name)
	}
	sort.Strings(tableNames)

	for _, tName := range tableNames {
		tbl := schema.Tables[tName]
		sb.WriteString(fmt.Sprintf("CREATE TABLE %s (\n", tbl.Name))
		for i, col := range tbl.Columns {
			pk := ""
			if col.IsPK {
				pk = " PRIMARY KEY"
			}
			nullable := ""
			if !col.IsNullable && !col.IsPK {
				nullable = " NOT NULL"
			}
			comma := ","
			if i == len(tbl.Columns)-1 && len(tbl.ForeignKeys) == 0 {
				comma = ""
			}
			sb.WriteString(fmt.Sprintf("    %s %s%s%s%s\n", col.Name, strings.ToUpper(col.DataType), pk, nullable, comma))
		}
		for i, fk := range tbl.ForeignKeys {
			comma := ","
			if i == len(tbl.ForeignKeys)-1 {
				comma = ""
			}
			constraintName := fk.Name
			if constraintName == "" {
				constraintName = fmt.Sprintf("fk_%s_%s", fk.FromTable, fk.FromColumn)
			}
			sb.WriteString(fmt.Sprintf("    CONSTRAINT %s FOREIGN KEY (%s) REFERENCES %s(%s)%s\n",
				constraintName, fk.FromColumn, fk.ToTable, fk.ToColumn, comma))
		}
		sb.WriteString(");\n\n")
	}

	return sb.String()
}

// LoadHybridSchema attempts to load the schema from workspace SQL files, falling back to a default sample schema.
func LoadHybridSchema(workspaceDir string) *SchemaAST {
	if workspaceDir != "" {
		var sqlFiles []string
		_ = filepath.Walk(workspaceDir, func(path string, info os.FileInfo, err error) error {
			if err != nil {
				return nil
			}
			if info.IsDir() {
				name := info.Name()
				if name == ".git" || name == "node_modules" || name == "vendor" || name == ".gemini" {
					return filepath.SkipDir
				}
				return nil
			}
			ext := strings.ToLower(filepath.Ext(path))
			if ext == ".sql" || ext == ".ddl" {
				sqlFiles = append(sqlFiles, path)
			}
			return nil
		})

		if len(sqlFiles) > 0 {
			combinedSchema := NewSchemaAST()
			foundAny := false
			for _, file := range sqlFiles {
				data, err := os.ReadFile(file)
				if err == nil && len(data) > 0 {
					parsed := ParseSQLDDL(string(data))
					if parsed != nil && len(parsed.Tables) > 0 {
						foundAny = true
						for name, tbl := range parsed.Tables {
							combinedSchema.Tables[name] = tbl
						}
					}
				}
			}
			if foundAny && len(combinedSchema.Tables) > 0 {
				return combinedSchema
			}
		}
	}

	// Default demo schema if no SQL files found
	return DefaultSampleSchema()
}

// DefaultSampleSchema provides an initial relational schema model.
func DefaultSampleSchema() *SchemaAST {
	s := NewSchemaAST()
	s.Tables["users"] = &Table{
		Name: "users",
		Columns: []Column{
			{Name: "id", DataType: "uuid", IsPK: true},
			{Name: "email", DataType: "varchar(255)", IsNullable: false},
			{Name: "name", DataType: "varchar(100)", IsNullable: true},
		},
	}
	s.Tables["orders"] = &Table{
		Name: "orders",
		Columns: []Column{
			{Name: "id", DataType: "uuid", IsPK: true},
			{Name: "user_id", DataType: "uuid", IsNullable: false},
			{Name: "total", DataType: "numeric(10,2)", IsNullable: false},
		},
		ForeignKeys: []ForeignKey{
			{Name: "fk_orders_user", FromTable: "orders", FromColumn: "user_id", ToTable: "users", ToColumn: "id"},
		},
	}
	s.Tables["products"] = &Table{
		Name: "products",
		Columns: []Column{
			{Name: "id", DataType: "uuid", IsPK: true},
			{Name: "title", DataType: "varchar(200)", IsNullable: false},
			{Name: "price", DataType: "numeric(10,2)", IsNullable: false},
		},
	}
	return s
}
