package plugin

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
)

// RunCLI handles 'tahr plugin' subcommands.
func RunCLI(args []string) error {
	if len(args) == 0 {
		PrintUsage()
		return nil
	}

	subcmd := args[0]
	subargs := args[1:]

	switch subcmd {
	case "init":
		if len(subargs) < 1 {
			return fmt.Errorf("usage: tahr plugin init <plugin-name> [--lang=go|declarative]")
		}
		name := subargs[0]
		lang := "declarative"
		if len(subargs) > 1 && subargs[1] == "--lang=go" {
			lang = "go"
		}
		return InitPlugin(name, lang)

	case "pack":
		srcDir := "."
		if len(subargs) >= 1 {
			srcDir = subargs[0]
		}
		manifestPath := filepath.Join(srcDir, "plugin.json")
		m, err := LoadManifest(manifestPath)
		if err != nil {
			return fmt.Errorf("plugin manifest error: %w", err)
		}
		destArchive := fmt.Sprintf("%s.tahr", m.ID)
		if len(subargs) >= 2 {
			destArchive = subargs[1]
		}
		if err := PackDirectory(srcDir, destArchive); err != nil {
			return err
		}
		fmt.Printf("Successfully packed plugin into %s\n", destArchive)
		return nil

	case "pack-all":
		pluginsDir := "plugins"
		if len(subargs) >= 1 {
			pluginsDir = subargs[0]
		}
		entries, err := os.ReadDir(pluginsDir)
		if err != nil {
			return fmt.Errorf("read plugins directory: %w", err)
		}
		count := 0
		for _, e := range entries {
			if !e.IsDir() {
				continue
			}
			pDir := filepath.Join(pluginsDir, e.Name())
			manifestPath := filepath.Join(pDir, "plugin.json")
			m, err := LoadManifest(manifestPath)
			if err != nil {
				continue
			}
			destArchive := filepath.Join(pluginsDir, fmt.Sprintf("%s.tahr", m.ID))
			if err := PackDirectory(pDir, destArchive); err != nil {
				return fmt.Errorf("failed to pack %s: %w", m.ID, err)
			}
			fmt.Printf("✔ Packed %s -> %s\n", m.ID, destArchive)
			count++
		}
		fmt.Printf("Packed %d plugins successfully\n", count)
		return nil


	case "install":
		if len(subargs) < 1 {
			return fmt.Errorf("usage: tahr plugin install <package.tahr>")
		}
		mgr, err := NewManager("")
		if err != nil {
			return err
		}
		defer mgr.Close()
		m, err := mgr.Install(subargs[0])
		if err != nil {
			return err
		}
		fmt.Printf("Installed plugin: %s (%s) v%s\n", m.Name, m.ID, m.Version)
		return nil

	case "link":
		if len(subargs) < 1 {
			return fmt.Errorf("usage: tahr plugin link <plugin-directory>")
		}
		mgr, err := NewManager("")
		if err != nil {
			return err
		}
		defer mgr.Close()
		m, err := mgr.Link(subargs[0])
		if err != nil {
			return err
		}
		fmt.Printf("Linked development plugin: %s (%s) v%s\n", m.Name, m.ID, m.Version)
		return nil

	case "list":
		mgr, err := NewManager("")
		if err != nil {
			return err
		}
		defer mgr.Close()
		plugins := mgr.InstalledPlugins()
		fmt.Printf("Installed plugins (%d):\n", len(plugins))
		for _, p := range plugins {
			fmt.Printf("  • %s (%s) v%s\n", p.Name, p.ID, p.Version)
		}
		return nil

	case "help", "--help", "-h":
		PrintUsage()
		return nil

	default:
		PrintUsage()
		return fmt.Errorf("unknown plugin command: %s", subcmd)
	}
}

// InitPlugin scaffolds a new plugin project.
func InitPlugin(name, lang string) error {
	dir := name
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}

	manifest := Manifest{
		ID:          name,
		Name:        fmt.Sprintf("%s Extension", name),
		Version:     "1.0.0",
		Author:      "user",
		Description: fmt.Sprintf("Extension for %s", name),
		Languages: []LanguageConfig{
			{
				ID:           name,
				Extensions:   []string{fmt.Sprintf(".%s", name)},
				CommentToken: "//",
			},
		},
		LSP: &LSPConfig{
			Command: fmt.Sprintf("%s-language-server", name),
			Args:    []string{"--stdio"},
		},
	}

	if lang == "go" {
		manifest.WASMEntry = "plugin.wasm"
		manifest.Capabilities = []string{"process:exec"}

		// Generate sample Go plugin source using tahr_sdk
		mainGo := fmt.Sprintf(`package main

import (
	"tahr/pkg/tahr_sdk"
)

func main() {
	tahr_sdk.Log("Initializing plugin: %s")

	tahr_sdk.RegisterCommand("%s.insertHeader", func() {
		_ = tahr_sdk.InsertAtCursor("// Header generated by %s\n")
		tahr_sdk.Log("Header inserted")
	})
}
`, name, name, name)
		_ = os.WriteFile(filepath.Join(dir, "main.go"), []byte(mainGo), 0644)
	}

	data, _ := json.MarshalIndent(manifest, "", "  ")
	if err := os.WriteFile(filepath.Join(dir, "plugin.json"), data, 0644); err != nil {
		return err
	}

	fmt.Printf("Initialized new %s plugin project in ./%s/\n", lang, dir)
	return nil
}

// PrintUsage prints the CLI help for tahr plugin.
func PrintUsage() {
	fmt.Println("Usage: tahr plugin <command> [args...]")
	fmt.Println("\nCommands:")
	fmt.Println("  init <name> [--lang=go]   Scaffold a new plugin directory")
	fmt.Println("  pack [dir] [archive.tahr] Pack directory into a .tahr Zstandard bundle")
	fmt.Println("  pack-all [dir]            Pack all plugin subdirectories into .tahr archives")
	fmt.Println("  install <archive.tahr>    Install a plugin package")
	fmt.Println("  link <dir>                Link a development directory for hot-reload")
	fmt.Println("  list                      List all installed plugins")
}
