package plugin

import (
	"encoding/json"
	"fmt"
	"os"
	"strings"
)

// ToolchainConfig describes how the plugin provides its toolchain name, environment, and version in the status bar.
type ToolchainConfig struct {
	Name        string   `json:"name,omitempty"`        // Display name: e.g. "Python", "Rust", "Go", "TypeScript"
	EnvMarkers  []string `json:"env_markers,omitempty"`  // Workspace folder markers: e.g. [".venv", "venv", "env"]
	EnvVariable string   `json:"env_variable,omitempty"` // Environment variable to check: e.g. "VIRTUAL_ENV"
	EnvSuffix   string   `json:"env_suffix,omitempty"`   // Suffix when env marker is found: e.g. " (.venv)"
	DynamicSDK  string   `json:"dynamic_sdk,omitempty"`  // Identifier for dynamic SDK query: e.g. "go"
}

// LanguageConfig describes language support configurations.
type LanguageConfig struct {
	ID           string           `json:"id"`
	Name         string           `json:"name,omitempty"`
	Extensions   []string         `json:"extensions"`
	Filenames    []string         `json:"filenames,omitempty"`
	Grammar      string           `json:"grammar,omitempty"`
	Highlights   string           `json:"highlights,omitempty"`
	Indents      string           `json:"indents,omitempty"`
	CommentToken string           `json:"comment_token,omitempty"`
	BuildCmd     string           `json:"build_cmd,omitempty"`
	BuildArgs    []string         `json:"build_args,omitempty"`
	RunCmd       string           `json:"run_cmd,omitempty"`
	RunArgs      []string         `json:"run_args,omitempty"`
	InstallCmd   string           `json:"install_cmd,omitempty"`
	Toolchain    *ToolchainConfig `json:"toolchain,omitempty"`
}

// LSPConfig describes language server launch parameters.
type LSPConfig struct {
	ServerName  string   `json:"server_name,omitempty"`
	Command     string   `json:"command"`
	Args        []string `json:"args"`
	RootMarkers []string `json:"root_markers,omitempty"`
	InstallCmd  string   `json:"install_cmd,omitempty"`
}

// DAPConfig describes debug adapter launch parameters.
type DAPConfig struct {
	AdapterName string   `json:"adapter_name,omitempty"`
	Command     string   `json:"command"`
	Args        []string `json:"args"`
	InstallCmd  string   `json:"install_cmd,omitempty"`
}

// ThemeConfig describes a theme palette defined by a plugin.
type ThemeConfig struct {
	ID     string            `json:"id"`
	Name   string            `json:"name"`
	Colors map[string]string `json:"colors"`
}

// LaunchTemplate describes a predefined run/debug configuration from a plugin.
type LaunchTemplate struct {
	Name          string            `json:"name"`
	Type          string            `json:"type"`
	Request       string            `json:"request"`
	Target        string            `json:"target"`
	Args          []string          `json:"args,omitempty"`
	Env           map[string]string `json:"env,omitempty"`
	Console       string            `json:"console,omitempty"`
	PreLaunchTask string            `json:"preLaunchTask,omitempty"`
}

// SDKAutodetectConfig describes how the plugin detects SDK binaries.
type SDKAutodetectConfig struct {
	Binaries     []string `json:"binaries,omitempty"`
	WindowsPaths []string `json:"windows_paths,omitempty"`
	UnixPaths    []string `json:"unix_paths,omitempty"`
}

// PluginSettingSchema defines the structure of a configuration field contributed by a plugin.
type PluginSettingSchema struct {
	Type        string `json:"type"` // "string", "bool", "int"
	Default     any    `json:"default"`
	Description string `json:"description"`
}

// ProjectTemplateFile defines an individual file to be generated by a template.
type ProjectTemplateFile struct {
	Path    string `json:"path"`
	Content string `json:"content"`
}

// ProjectTemplate defines a project scaffolding archetype provided by a plugin.
type ProjectTemplate struct {
	ID            string                `json:"id"`
	Name          string                `json:"name"`
	Description   string                `json:"description"`
	Category      string                `json:"category,omitempty"`
	Icon          string                `json:"icon,omitempty"`
	PluginID      string                `json:"plugin_id,omitempty"`
	DefaultModule string                `json:"default_module,omitempty"`
	Files         []ProjectTemplateFile `json:"files,omitempty"`
	PostCreateCmd string                `json:"post_create_cmd,omitempty"`
}

// LocalizationConfig defines a language pack provided by a plugin.
type LocalizationConfig struct {
	Locale string `json:"locale"` // e.g. "ru", "es", "de"
	Name   string `json:"name"`   // e.g. "Русский", "Español"
	File   string `json:"file"`   // path relative to plugin root, e.g. "locales/ru.json"
}

// Source tier constants for plugin precedence hierarchy.
const (
	TierBuiltin = 1 // Bundled / distribution packages
	TierUser    = 2 // User global directory (~/.config/tahr/plugins)
	TierLink    = 3 // Developer directory link (tahr plugin link)
	TierProject = 4 // Workspace project directory (<workspace>/.tahr/plugins)
)

// ViewContribution describes a custom UI view/tab contributed by a plugin.
type ViewContribution struct {
	ContainerID string `json:"container_id"`
	TabID       string `json:"tab_id"`
	Title       string `json:"title"`
	Icon        string `json:"icon,omitempty"`
	Slot        string `json:"slot,omitempty"` // e.g. "workbench.slot.editor-area", "workbench.slot.left-sidebar"
}

// ToolWindowConfig defines a docked panel tool window contributed by an extension.
type ToolWindowConfig struct {
	ID       string `json:"id"`
	Title    string `json:"title"`
	Icon     string `json:"icon"`
	Position string `json:"position"` // "left", "right", "bottom"
}

// ContributesConfig holds all declarative contribution points of an extension.
type ContributesConfig struct {
	Views []ViewContribution `json:"views,omitempty"`
}

// Manifest represents the declarative metadata of a .tahr extension.
type Manifest struct {
	ID               string                         `json:"id"`
	Name             string                         `json:"name"`
	Version          string                         `json:"version"`
	Author           string                         `json:"author,omitempty"`
	Description      string                         `json:"description,omitempty"`
	Category         string                         `json:"category,omitempty"`
	Type             string                         `json:"type,omitempty"`             // "language", "tool", "theme", "i18n"
	TargetLanguages  []string                       `json:"target_languages,omitempty"` // For auxiliary tools targeting languages (e.g. "go")
	Capabilities     []string                       `json:"capabilities,omitempty"`     // e.g. "fs:read", "process:exec"
	Languages        []LanguageConfig               `json:"languages,omitempty"`
	Themes           []ThemeConfig                  `json:"themes,omitempty"`
	LSP              *LSPConfig                     `json:"lsp,omitempty"`
	DAP              *DAPConfig                     `json:"dap,omitempty"`
	LaunchTemplates  []LaunchTemplate               `json:"launchTemplates,omitempty"`
	ProjectTemplates []ProjectTemplate              `json:"project_templates,omitempty"`
	SDKAutodetect    *SDKAutodetectConfig           `json:"sdk_autodetect,omitempty"`
	Settings         map[string]PluginSettingSchema `json:"settings,omitempty"`
	Localizations    []LocalizationConfig           `json:"localizations,omitempty"`
	Toolchain        *ToolchainConfig               `json:"toolchain,omitempty"`
	WASMEntry        string                         `json:"wasm_entry,omitempty"`
	ToolWindows      []ToolWindowConfig             `json:"tool_windows,omitempty"`
	Contributes      *ContributesConfig             `json:"contributes,omitempty"`

	SourceTier       int                            `json:"-"` // Precedence tier: TierBuiltin, TierUser, TierLink, TierProject
}

// IsLanguageProvider reports whether this plugin contributes primary language support.
func (m *Manifest) IsLanguageProvider() bool {
	if m == nil {
		return false
	}
	if strings.EqualFold(m.Type, "language") {
		return true
	}
	// Implicit: if type is unspecified, treat as language provider if it declares languages.
	return m.Type == "" && len(m.Languages) > 0
}

// TargetsLanguage checks if this plugin provides or targets the given language ID.
func (m *Manifest) TargetsLanguage(langID string) bool {
	if m == nil || langID == "" {
		return false
	}
	normID := strings.ToLower(langID)
	for _, l := range m.Languages {
		if strings.ToLower(l.ID) == normID {
			return true
		}
	}
	for _, tl := range m.TargetLanguages {
		if strings.ToLower(tl) == normID {
			return true
		}
	}
	return false
}

// LoadManifest reads and parses a plugin.json file.
func LoadManifest(filePath string) (*Manifest, error) {
	data, err := os.ReadFile(filePath)
	if err != nil {
		return nil, fmt.Errorf("read manifest: %w", err)
	}

	var m Manifest
	if err := json.Unmarshal(data, &m); err != nil {
		return nil, fmt.Errorf("parse manifest JSON: %w", err)
	}

	if m.ID == "" {
		return nil, fmt.Errorf("manifest missing required 'id' field")
	}

	return &m, nil
}

// HasCapability checks whether a capability is declared in the manifest.
func (m *Manifest) HasCapability(capName string) bool {
	for _, c := range m.Capabilities {
		if c == capName {
			return true
		}
	}
	return false
}
