package plugin

import (
	"encoding/json"
	"fmt"
	"os"
)

// LanguageConfig describes language support configurations.
type LanguageConfig struct {
	ID           string   `json:"id"`
	Extensions   []string `json:"extensions"`
	Filenames    []string `json:"filenames,omitempty"`
	Grammar      string   `json:"grammar,omitempty"`
	Highlights   string   `json:"highlights,omitempty"`
	Indents      string   `json:"indents,omitempty"`
	CommentToken string   `json:"comment_token,omitempty"`
	BuildCmd     string   `json:"build_cmd,omitempty"`
	BuildArgs    []string `json:"build_args,omitempty"`
	RunCmd       string   `json:"run_cmd,omitempty"`
	RunArgs      []string `json:"run_args,omitempty"`
	InstallCmd   string   `json:"install_cmd,omitempty"`
}

// LSPConfig describes language server launch parameters.
type LSPConfig struct {
	ServerName  string   `json:"server_name,omitempty"`
	Command     string   `json:"command"`
	Args        []string `json:"args"`
	RootMarkers []string `json:"root_markers,omitempty"`
	InstallCmd  string   `json:"install_cmd,omitempty"`
}

// DAPConfig describes debug adapter launch parameters.
type DAPConfig struct {
	AdapterName string   `json:"adapter_name,omitempty"`
	Command     string   `json:"command"`
	Args        []string `json:"args"`
	InstallCmd  string   `json:"install_cmd,omitempty"`
}

// ThemeConfig describes a theme palette defined by a plugin.
type ThemeConfig struct {
	ID     string            `json:"id"`
	Name   string            `json:"name"`
	Colors map[string]string `json:"colors"`
}

// LaunchTemplate describes a predefined run/debug configuration from a plugin.
type LaunchTemplate struct {
	Name          string            `json:"name"`
	Type          string            `json:"type"`
	Request       string            `json:"request"`
	Target        string            `json:"target"`
	Args          []string          `json:"args,omitempty"`
	Env           map[string]string `json:"env,omitempty"`
	Console       string            `json:"console,omitempty"`
	PreLaunchTask string            `json:"preLaunchTask,omitempty"`
}

// SDKAutodetectConfig describes how the plugin detects SDK binaries.
type SDKAutodetectConfig struct {
	Binaries     []string `json:"binaries,omitempty"`
	WindowsPaths []string `json:"windows_paths,omitempty"`
	UnixPaths    []string `json:"unix_paths,omitempty"`
}

// PluginSettingSchema defines the structure of a configuration field contributed by a plugin.
type PluginSettingSchema struct {
	Type        string `json:"type"` // "string", "bool", "int"
	Default     any    `json:"default"`
	Description string `json:"description"`
}

// ProjectTemplateFile defines an individual file to be generated by a template.
type ProjectTemplateFile struct {
	Path    string `json:"path"`
	Content string `json:"content"`
}

// ProjectTemplate defines a project scaffolding archetype provided by a plugin.
type ProjectTemplate struct {
	ID            string                `json:"id"`
	Name          string                `json:"name"`
	Description   string                `json:"description"`
	Category      string                `json:"category,omitempty"`
	Icon          string                `json:"icon,omitempty"`
	PluginID      string                `json:"plugin_id,omitempty"`
	DefaultModule string                `json:"default_module,omitempty"`
	Files         []ProjectTemplateFile `json:"files,omitempty"`
	PostCreateCmd string                `json:"post_create_cmd,omitempty"`
}

// LocalizationConfig defines a language pack provided by a plugin.
type LocalizationConfig struct {
	Locale string `json:"locale"` // e.g. "ru", "es", "de"
	Name   string `json:"name"`   // e.g. "Русский", "Español"
	File   string `json:"file"`   // path relative to plugin root, e.g. "locales/ru.json"
}

// Manifest represents the declarative metadata of a .tahr extension.
type Manifest struct {
	ID               string                         `json:"id"`
	Name             string                         `json:"name"`
	Version          string                         `json:"version"`
	Author           string                         `json:"author,omitempty"`
	Description      string                         `json:"description,omitempty"`
	Category         string                         `json:"category,omitempty"`
	Capabilities     []string                       `json:"capabilities,omitempty"` // e.g. "fs:read", "process:exec"
	Languages        []LanguageConfig               `json:"languages,omitempty"`
	Themes           []ThemeConfig                  `json:"themes,omitempty"`
	LSP              *LSPConfig                     `json:"lsp,omitempty"`
	DAP              *DAPConfig                     `json:"dap,omitempty"`
	LaunchTemplates  []LaunchTemplate               `json:"launchTemplates,omitempty"`
	ProjectTemplates []ProjectTemplate              `json:"project_templates,omitempty"`
	SDKAutodetect    *SDKAutodetectConfig           `json:"sdk_autodetect,omitempty"`
	Settings         map[string]PluginSettingSchema `json:"settings,omitempty"`
	Localizations    []LocalizationConfig           `json:"localizations,omitempty"`
	WASMEntry        string                         `json:"wasm_entry,omitempty"`
}

// LoadManifest reads and parses a plugin.json file.
func LoadManifest(filePath string) (*Manifest, error) {
	data, err := os.ReadFile(filePath)
	if err != nil {
		return nil, fmt.Errorf("read manifest: %w", err)
	}

	var m Manifest
	if err := json.Unmarshal(data, &m); err != nil {
		return nil, fmt.Errorf("parse manifest JSON: %w", err)
	}

	if m.ID == "" {
		return nil, fmt.Errorf("manifest missing required 'id' field")
	}

	return &m, nil
}

// HasCapability checks whether a capability is declared in the manifest.
func (m *Manifest) HasCapability(capName string) bool {
	for _, c := range m.Capabilities {
		if c == capName {
			return true
		}
	}
	return false
}
